#!/usr/bin/env python3
"""
Data Readers for EDI Customization Layer
========================================

This module provides readers for comprehensive EDI data in various formats
(XML, CSV, JSON) generated by the main EDIFACT parser.

Author: EDIFACT Parser Team
Version: 1.0.0
"""

import json
import csv
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, List, Any, Optional, Union
from abc import ABC, abstractmethod
import logging

logger = logging.getLogger(__name__)


class DataReader(ABC):
    """Abstract base class for data readers"""
    
    @abstractmethod
    def read(self, source: Union[str, Path]) -> Dict[str, Any]:
        """Read data from source and return structured data"""
        pass
    
    @abstractmethod
    def validate_format(self, source: Union[str, Path]) -> bool:
        """Validate if source is in expected format"""
        pass


class XMLDataReader(DataReader):
    """Reader for comprehensive XML EDI data"""
    
    def __init__(self):
        self.logger = logging.getLogger(f"{__name__}.XMLDataReader")
    
    def read(self, source: Union[str, Path]) -> Dict[str, Any]:
        """Read XML data and convert to structured format"""
        try:
            tree = ET.parse(source)
            root = tree.getroot()
            
            data = {
                'format': 'xml',
                'source': str(source),
                'message_info': self._extract_message_info(root),
                'interchange_info': self._extract_interchange_info(root),
                'segments': self._extract_segments(root),
                'business_data': self._extract_business_data(root),
                'statistics': self._extract_statistics(root)
            }
            
            self.logger.info(f"Successfully read XML data from {source}")
            return data
            
        except Exception as e:
            self.logger.error(f"Error reading XML data from {source}: {e}")
            raise
    
    def validate_format(self, source: Union[str, Path]) -> bool:
        """Validate XML format"""
        try:
            tree = ET.parse(source)
            root = tree.getroot()
            
            # Check for expected structure
            expected_elements = ['MessageInfo', 'InterchangeInfo', 'Segments']
            for element in expected_elements:
                if root.find(f".//{element}") is None:
                    return False
            
            return True
            
        except Exception:
            return False
    
    def _extract_message_info(self, root: ET.Element) -> Dict[str, Any]:
        """Extract message information from XML"""
        message_info = {}
        
        # Try different possible locations for message info
        message_elem = root.find('.//MessageInfo')
        if message_elem is not None:
            for child in message_elem:
                message_info[child.tag.lower()] = child.text
        
        # Also check root attributes
        for attr, value in root.attrib.items():
            if attr.lower().startswith('message'):
                message_info[attr.lower()] = value
        
        return message_info
    
    def _extract_interchange_info(self, root: ET.Element) -> Dict[str, Any]:
        """Extract interchange information from XML"""
        interchange_info = {}
        
        interchange_elem = root.find('.//InterchangeInfo')
        if interchange_elem is not None:
            for child in interchange_elem:
                interchange_info[child.tag.lower()] = child.text
        
        # Also check for UNB segment data
        unb_elem = root.find('.//Segment[@tag="UNB"]')
        if unb_elem is not None:
            interchange_info.update(self._extract_unb_data(unb_elem))
        
        return interchange_info
    
    def _extract_segments(self, root: ET.Element) -> List[Dict[str, Any]]:
        """Extract all segments from XML"""
        segments = []
        
        segments_container = root.find('.//Segments')
        if segments_container is not None:
            for segment_elem in segments_container.findall('.//Segment'):
                segment_data = {
                    'tag': segment_elem.get('tag', ''),
                    'position': int(segment_elem.get('position', 0)),
                    'semantic_name': segment_elem.get('semantic_name', ''),
                    'elements': self._extract_elements(segment_elem)
                }
                segments.append(segment_data)
        
        return segments
    
    def _extract_elements(self, segment_elem: ET.Element) -> List[Dict[str, Any]]:
        """Extract elements from a segment"""
        elements = []
        
        for elem in segment_elem:
            if elem.tag.startswith('Element') or elem.tag.startswith('Component'):
                element_data = {
                    'name': elem.tag,
                    'value': elem.text or '',
                    'position': int(elem.get('position', 0)),
                    'components': self._extract_components(elem)
                }
                elements.append(element_data)
        
        return elements
    
    def _extract_components(self, element_elem: ET.Element) -> List[Dict[str, Any]]:
        """Extract components from an element"""
        components = []
        
        for comp in element_elem:
            if comp.tag.startswith('Component'):
                component_data = {
                    'name': comp.tag,
                    'value': comp.text or '',
                    'position': int(comp.get('position', 0))
                }
                components.append(component_data)
        
        return components
    
    def _extract_business_data(self, root: ET.Element) -> Dict[str, Any]:
        """Extract business data from XML"""
        business_data = {}
        
        business_elem = root.find('.//BusinessData')
        if business_elem is not None:
            for child in business_elem:
                if child.tag == 'Parties':
                    business_data['parties'] = self._extract_parties(child)
                elif child.tag == 'LineItems':
                    business_data['line_items'] = self._extract_line_items(child)
                elif child.tag == 'Dates':
                    business_data['dates'] = self._extract_dates(child)
                elif child.tag == 'References':
                    business_data['references'] = self._extract_references(child)
                elif child.tag == 'Totals':
                    business_data['totals'] = self._extract_totals(child)
        
        return business_data
    
    def _extract_parties(self, parties_elem: ET.Element) -> Dict[str, Dict[str, Any]]:
        """Extract party information"""
        parties = {}
        
        for party in parties_elem.findall('Party'):
            qualifier = party.get('qualifier', '')
            party_data = {
                'id': party.findtext('ID', ''),
                'name': party.findtext('Name', ''),
                'address': party.findtext('Address', ''),
                'city': party.findtext('City', ''),
                'postal_code': party.findtext('PostalCode', ''),
                'country': party.findtext('Country', '')
            }
            parties[qualifier] = party_data
        
        return parties
    
    def _extract_line_items(self, items_elem: ET.Element) -> List[Dict[str, Any]]:
        """Extract line items"""
        line_items = []
        
        for item in items_elem.findall('LineItem'):
            item_data = {
                'line_number': item.findtext('LineNumber', ''),
                'item_id': item.findtext('ItemID', ''),
                'description': item.findtext('Description', ''),
                'quantity': item.findtext('Quantity', ''),
                'unit_price': item.findtext('UnitPrice', ''),
                'total_amount': item.findtext('TotalAmount', '')
            }
            line_items.append(item_data)
        
        return line_items
    
    def _extract_dates(self, dates_elem: ET.Element) -> Dict[str, str]:
        """Extract date information"""
        dates = {}
        
        for date in dates_elem.findall('Date'):
            qualifier = date.get('qualifier', '')
            dates[qualifier] = date.text or ''
        
        return dates
    
    def _extract_references(self, refs_elem: ET.Element) -> Dict[str, str]:
        """Extract reference information"""
        references = {}
        
        for ref in refs_elem.findall('Reference'):
            qualifier = ref.get('qualifier', '')
            references[qualifier] = ref.text or ''
        
        return references
    
    def _extract_totals(self, totals_elem: ET.Element) -> Dict[str, str]:
        """Extract total amounts"""
        totals = {}
        
        for total in totals_elem.findall('Total'):
            qualifier = total.get('qualifier', '')
            totals[qualifier] = total.text or ''
        
        return totals
    
    def _extract_statistics(self, root: ET.Element) -> Dict[str, Any]:
        """Extract processing statistics"""
        statistics = {}
        
        stats_elem = root.find('.//Statistics')
        if stats_elem is not None:
            for child in stats_elem:
                statistics[child.tag.lower()] = child.text
        
        return statistics
    
    def _extract_unb_data(self, unb_elem: ET.Element) -> Dict[str, Any]:
        """Extract UNB segment data"""
        unb_data = {}
        
        # Extract sender and receiver from UNB elements
        elements = unb_elem.findall('.//Element')
        if len(elements) >= 4:
            unb_data['sender_id'] = elements[1].text or ''
            unb_data['recipient_id'] = elements[2].text or ''
            unb_data['preparation_date'] = elements[3].text or ''
        
        return unb_data


class CSVDataReader(DataReader):
    """Reader for comprehensive CSV EDI data"""
    
    def __init__(self):
        self.logger = logging.getLogger(f"{__name__}.CSVDataReader")
    
    def read(self, source: Union[str, Path]) -> Dict[str, Any]:
        """Read CSV data and convert to structured format"""
        try:
            data = {
                'format': 'csv',
                'source': str(source),
                'segments': [],
                'message_info': {},
                'interchange_info': {},
                'business_data': {}
            }
            
            with open(source, 'r', encoding='utf-8') as csvfile:
                reader = csv.DictReader(csvfile)
                
                for row in reader:
                    segment_data = {
                        'tag': row.get('SegmentTag', ''),
                        'position': int(row.get('Position', 0)),
                        'semantic_name': row.get('SemanticName', ''),
                        'element_count': int(row.get('ElementCount', 0)),
                        'raw_data': row
                    }
                    data['segments'].append(segment_data)
            
            # Extract message info from first segment if available
            if data['segments']:
                first_segment = data['segments'][0]
                if 'MessageType' in first_segment['raw_data']:
                    data['message_info']['type'] = first_segment['raw_data']['MessageType']
                if 'Sender' in first_segment['raw_data']:
                    data['interchange_info']['sender_id'] = first_segment['raw_data']['Sender']
                if 'Recipient' in first_segment['raw_data']:
                    data['interchange_info']['recipient_id'] = first_segment['raw_data']['Recipient']
            
            self.logger.info(f"Successfully read CSV data from {source}")
            return data
            
        except Exception as e:
            self.logger.error(f"Error reading CSV data from {source}: {e}")
            raise
    
    def validate_format(self, source: Union[str, Path]) -> bool:
        """Validate CSV format"""
        try:
            with open(source, 'r', encoding='utf-8') as csvfile:
                reader = csv.DictReader(csvfile)
                
                # Check for expected columns
                expected_columns = ['SegmentTag', 'Position']
                fieldnames = reader.fieldnames or []
                
                for col in expected_columns:
                    if col not in fieldnames:
                        return False
                
                return True
                
        except Exception:
            return False


class JSONDataReader(DataReader):
    """Reader for comprehensive JSON EDI data"""
    
    def __init__(self):
        self.logger = logging.getLogger(f"{__name__}.JSONDataReader")
    
    def read(self, source: Union[str, Path]) -> Dict[str, Any]:
        """Read JSON data and convert to structured format"""
        try:
            with open(source, 'r', encoding='utf-8') as jsonfile:
                data = json.load(jsonfile)
            
            # Ensure consistent structure
            structured_data = {
                'format': 'json',
                'source': str(source),
                'message_info': data.get('message_info', {}),
                'interchange_info': data.get('interchange_info', {}),
                'segments': data.get('segments', []),
                'business_data': data.get('business_data', {}),
                'statistics': data.get('statistics', {})
            }
            
            self.logger.info(f"Successfully read JSON data from {source}")
            return structured_data
            
        except Exception as e:
            self.logger.error(f"Error reading JSON data from {source}: {e}")
            raise
    
    def validate_format(self, source: Union[str, Path]) -> bool:
        """Validate JSON format"""
        try:
            with open(source, 'r', encoding='utf-8') as jsonfile:
                data = json.load(jsonfile)
            
            # Check for expected structure
            expected_keys = ['message_info', 'segments']
            for key in expected_keys:
                if key not in data:
                    return False
            
            return True
            
        except Exception:
            return False


class DataReaderFactory:
    """Factory for creating appropriate data readers"""
    
    _readers = {
        'xml': XMLDataReader,
        'csv': CSVDataReader,
        'json': JSONDataReader
    }
    
    @classmethod
    def create_reader(cls, format_type: str) -> DataReader:
        """Create a reader for the specified format"""
        if format_type.lower() not in cls._readers:
            raise ValueError(f"Unsupported format: {format_type}")
        
        return cls._readers[format_type.lower()]()
    
    @classmethod
    def auto_detect_format(cls, source: Union[str, Path]) -> Optional[str]:
        """Auto-detect format based on file extension and content"""
        source_path = Path(source)
        extension = source_path.suffix.lower()
        
        # Try by extension first
        if extension == '.xml':
            reader = cls.create_reader('xml')
            if reader.validate_format(source):
                return 'xml'
        elif extension == '.csv':
            reader = cls.create_reader('csv')
            if reader.validate_format(source):
                return 'csv'
        elif extension == '.json':
            reader = cls.create_reader('json')
            if reader.validate_format(source):
                return 'json'
        
        # Try all formats if extension-based detection fails
        for format_type in cls._readers.keys():
            try:
                reader = cls.create_reader(format_type)
                if reader.validate_format(source):
                    return format_type
            except Exception:
                continue
        
        return None
    
    @classmethod
    def read_data(cls, source: Union[str, Path], format_type: Optional[str] = None) -> Dict[str, Any]:
        """Read data with automatic format detection if needed"""
        if format_type is None:
            format_type = cls.auto_detect_format(source)
            if format_type is None:
                raise ValueError(f"Could not detect format for {source}")
        
        reader = cls.create_reader(format_type)
        return reader.read(source)


# Convenience functions
def read_xml_data(source: Union[str, Path]) -> Dict[str, Any]:
    """Convenience function to read XML data"""
    reader = XMLDataReader()
    return reader.read(source)


def read_csv_data(source: Union[str, Path]) -> Dict[str, Any]:
    """Convenience function to read CSV data"""
    reader = CSVDataReader()
    return reader.read(source)


def read_json_data(source: Union[str, Path]) -> Dict[str, Any]:
    """Convenience function to read JSON data"""
    reader = JSONDataReader()
    return reader.read(source)


def read_edi_data(source: Union[str, Path], format_type: Optional[str] = None) -> Dict[str, Any]:
    """Convenience function to read EDI data with auto-detection"""
    return DataReaderFactory.read_data(source, format_type)

